name: install-lib

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        # - macos-12
        # - windows-2022
        ghc:
          - 9.10.1
        # - 9.8.2
        # - 9.6.5
        # - 9.4.8
        cabal:
          - 3.12.1.0
          - 3.10.3.0
        # - 3.10.2.1
        # - 3.8.1.0
        # - 3.6.2.0
      fail-fast: false

    steps:

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          cabal-update: true

      - uses: actions/checkout@v4

      - run: cabal install --lib
